---
title: "SanyujaR"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r Load_Libraries}
library("tidyverse")
library("lubridate")
library("dplyr")
library("ggplot2")
library("rpart")
```
```{r Load_Data}
lcdf= read.csv("~/Documents/R/lcData6m.csv")
```
```{r}
```

```{r Data_Grouping_and_Add_new_Variables}
# Derive new attributes like defaut rate, and something else

# Data grouping

lcdf <- lcdf %>%  filter(loan_status !="Current")
lcdf %>% group_by(loan_status, grade)%>% tally
tmp0 = lcdf %>% group_by(loan_status) %>% summarise(ncount = n())
tmp0$ncount = 100 * tmp0$ncount/nrow(lcdf)
tmp0$ncount_p = str_c(round(tmp0$ncount,2),"%")

count(lcdf,grade) 

lcdf %>% group_by(grade) %>% summarise(sum(loan_amnt)) 
lcdf %>% group_by(grade) %>% summarise (mean(loan_amnt))
lcdf%>% group_by(loan_status=="Charged Off") %>% tally()


```


```{r Data_Grouping_and_Add_new_Variables}


#Month wise distribution of the default_rate for 6 months:
#lcdf$issue_d<-gsub("T00:00:00Z","",lcdf$issue_d)
#lcdf$issue_d<-parse_date_time(lcdf$issue_d, "ymd")


lcdf$issue_m = as.numeric(sapply( lcdf$issue_d ,function(x){str_split(x,"-")[[1]][2]}))

displayInterestByGrade <- function(dt){
    g1 = dt %>% filter(loan_status == "Charged Off") %>% group_by(grade) %>% summarise(default_count = n())
    g2 = dt %>% group_by(grade) %>% summarise(count = n(),int_rate=mean(int_rate))
    g2 %>% left_join(g1) %>% mutate(default_rate = 100*default_count/count) %>% select(grade,count,default_count,int_rate,default_rate)
}

#summary(lcdf$issue_m)
tmp1 = displayInterestByGrade(lcdf %>% filter(issue_m==1))
tmp2 = displayInterestByGrade(lcdf %>% filter(issue_m==2))
tmp3 = displayInterestByGrade(lcdf %>% filter(issue_m==3))
tmp4 = displayInterestByGrade(lcdf %>% filter(issue_m==4))
tmp5 = displayInterestByGrade(lcdf %>% filter(issue_m==5))
tmp6 = displayInterestByGrade(lcdf %>% filter(issue_m==6))
tmp1$issue_m=c(1,1,1,1,1,1,1)
tmp2$issue_m=c(2,2,2,2,2,2,2)
tmp3$issue_m=c(3,3,3,3,3,3,3)
tmp4$issue_m=c(4,4,4,4,4,4,4)
tmp5$issue_m=c(5,5,5,5,5,5,5)
tmp6$issue_m=c(6,6,6,6,6,6,6)

tmp = rbind(tmp1,tmp2,tmp3,tmp4,tmp5,tmp6)
#New attribute "default_rate" in x:

x=lcdf %>% group_by(grade) %>% summarise(default_rate= sum(loan_status=="Charged Off")/(nLoans=n())) # Defaut rate per grade

# month wise retrun on investment:

roi_1 = sum((lcdf %>% filter(issue_m==1))$total_pymnt)/sum((lcdf %>% filter(issue_m==1))$funded_amnt) - 1
roi_2 = sum((lcdf %>% filter(issue_m==2))$total_pymnt)/sum((lcdf %>% filter(issue_m==2))$funded_amnt) - 1
roi_3 = sum((lcdf %>% filter(issue_m==3))$total_pymnt)/sum((lcdf %>% filter(issue_m==3))$funded_amnt) - 1
roi_4 = sum((lcdf %>% filter(issue_m==4))$total_pymnt)/sum((lcdf %>% filter(issue_m==4))$funded_amnt) - 1
roi_5 = sum((lcdf %>% filter(issue_m==5))$total_pymnt)/sum((lcdf %>% filter(issue_m==5))$funded_amnt) - 1
roi_6 = sum((lcdf %>% filter(issue_m==6))$total_pymnt)/sum((lcdf %>% filter(issue_m==6))$funded_amnt) - 1


roi= rbind(roi_1,roi_2,roi_3,roi_4,roi_5,roi_6)
# grade wise roi:

lcdf$prediction = "Fully Paid"
createPerformanceTable <- function(dt){
    
    dt_pick = dt %>% filter(prediction == "Fully Paid")
    all_roi = sum(dt_pick$total_pymnt)/sum(dt_pick$funded_amnt) - 1

    temp_table = data.frame(grade=character(0),roi=numeric(0))
    for(g in c("A","B","C","D","E","F","G")){
        data_pick_grade = dt_pick %>% filter(grade==g)
        if(nrow(data_pick_grade)==0){
            temp_table = rbind(temp_table,data.frame(grade=g,roi=0))
        }
        else
        {
            data_grade = dt %>% filter(grade==g)
            roi = sum(data_pick_grade$total_pymnt)/sum(data_pick_grade$funded_amnt) - 1
            temp_table = rbind(temp_table,data.frame(grade=g,roi=roi))
        }
    }
    
    temp_table = rbind(temp_table,data.frame(grade="ALL",roi=all_roi ))
    
    return(temp_table)
}

grade_roi_table = createPerformanceTable(lcdf)

```


```{r Data_Exploration}

# DATA Exploration: Give title to all graphs.

ggplot(x, aes( x = x$default_rate, y= x$grade)) + geom_count() 

ggplot(lcdf, aes(loan_status), main="loan status" )+ geom_bar(aes(y = stat(count)))


ggplot(tmp0,aes(x=loan_status,y=ncount,fill=loan_status)) + geom_bar(stat="identity") +geom_text(aes(label=ncount_p),vjust = 2)

barplot(table(lcdf$loan_status, lcdf$grade),,main="Loan status with grades")
barplot(table(lcdf$loan_status, lcdf$sub_grade ),main="Loan status with sub grades")

p1 <- ggplot(data = lcdf, aes(loan_amnt, color = grade)) + geom_histogram(binwidth = 1000) + 
    facet_grid(grade ~ .)
p2 <- ggplot(data = lcdf, aes(loan_amnt, color = grade, fill = grade)) + geom_density(binwidth = 1000) + 
    facet_grid(grade ~ .)
plot(p1)
plot(p2)

ggplot(lcdf, aes( x = int_rate, color = grade, fill = grade)) + geom_histogram()
ggplot(lcdf, aes( x = int_rate, color = grade, fill = grade)) + geom_histogram()
ggplot(lcdf, aes(x = loan_amnt, color = grade, fill = grade)) + geom_histogram()
ggplot(lcdf, aes( x = int_rate, color = sub_grade, fill = sub_grade)) +geom_histogram()

ggplot(tmp, aes(x=grade, y=default_rate, fill=as.factor(issue_m))) + geom_bar(stat="identity",position="dodge") + ggtitle("Default Rate(%) for 6 months")

ggplot(grade_roi_table, aes(x=grade, y=roi, fill=grade))+ geom_bar(stat="identity",position="dodge") + ggtitle("ROI per Grade")
```
```{r Actual Return}
lcdf$last_pymnt_d<-paste(lcdf$last_pymnt_d, "-01", sep="")

lcdf$last_pymnt_d<-parse_date_time(lcdf$last_pymnt_d, "myd")


#Actual Term is a amount of time each person took to fully repay his loan. The deadline is 3 years, but some of them might have paid it earlier. Hence for ifelse statment: test: Fully paid? yes<- in how many years, No<- 3 years. 

lcdf$actualTerm <- ifelse(lcdf$loan_status=="Fully Paid", as.duration(lcdf$issue_d %--% lcdf$last_pymnt_d)/dyears(1),3)

head(lcdf$actualTerm)

#Annual percent return
lcdf$annRet<-((lcdf$total_pymnt-lcdf$funded_amnt)/lcdf$funded_amnt)*(12/36)*100
head(lcdf$annRet)
#Actual return: For this we will replace "12/36 (years)" by "actualterm/3 (years)"

lcdf$actualReturn<-((lcdf$total_pymnt-lcdf$funded_amnt)/lcdf$funded_amnt)*(lcdf$actualTerm/3)*100
head(lcdf$actualReturn)

```
```{r}
```





```{r Missing_Values}
#Missing Value and drop non important attributes
discard_column = c("collection_recovery_fee","emp_title",
                   "funded_amnt_inv","id",
                   "installment","last_credit_pull_d",
                   "last_fico_range_high","last_fico_range_low",
                   "last_pymnt_amnt","last_pymnt_d",
                   "loan_amnt","member_id",
                   "next_pymnt_d","num_tl_120dpd_2m",
                   "num_tl_30dpd","out_prncp",
                   "out_prncp_inv","recoveries",
                   "total_pymnt","total_pymnt_inv",
                   "total_rec_int","total_rec_late_fee",
                   "total_rec_prncp","url",
                   "zip_code"
                   )
lcdf = (lcdf[,!(names(lcd) %in% discard_column)])

```
```{r Leakage_Variables}
#Remove reduntant, leakage variable, Do a simple correlation. (Leakage variables: The varibales after the loan is issued)
#Leakage variables are like annual term, return , last paydate, last amnt etc
```
```{r Random_Forrest}
# do random forest and pick important variables.
#rpart is for decision trees, For  random forest we need to remove all the NA
```





